        <footer class="footer">
			<section class="container footer_center">
				<section class="row">
					<article class="span4" style="margin-top: -10px;">
						<figure style="margin-bottom: -5px;"><a href="http://www.continuum.io" title="Continuum Analytics"><img src="/img/footer_logo.png" alt="Continuum Analytics" width="134" height="64" class="footer_logo"/></a></figure>
						3801 Capital of Texas Highway South<br/>
						Suite 250<br/>
						Austin, TX 78704<br/>
						<br/>
						512.222.5440<br/>
						<a class="footer_links" href="mailto:&#x69;&#x6e;&#102;&#x6f;&#00064;&#x63;&#000111;&#110;&#x74;&#x69;&#x6e;&#x75;&#x75;&#000109;&#x2e;&#105;&#111;">&#x69;&#x6e;&#102;&#x6f;&#00064;&#x63;&#000111;&#110;&#x74;&#x69;&#x6e;&#x75;&#x75;&#000109;&#x2e;&#105;&#111;</a><br/>
						<section class="footer_social_media">
                            <a href="http://plus.google.com/108011804375544975017" title="Circle Continuum Analytics on Google+" target="_blank"><img src="/img/gplus_header.png" alt="Circle Continuum Analytics on Google+" width="33" height="33"></a>
                            <a href="http://www.twitter.com/continuumio" title="Follow @continuumio on Twitter" target="_blank"><img src="/img/twitter_header.png" alt="Follow @continuumio on Twitter" width="33" height="33"></a>
                            <a href="http://www.linkedin.com/company/continuum-analytics-inc-" title="Follow Continuum Analytics on LinkedIn" target="_blank"><img src="/img/linkedin_header.png" alt="Follow Continuum Analytics on LinkedIn" width="33" height="33"></a>
                            <a href="http://www.facebook.com/ContinuumAnalytics" title="Like Continuum Analytics on Facebook" target="_blank"><img src="/img/facebook_header.png" alt="Like Continuum Analytics on Facebook" width="33" height="33"></a>
                            <!--<a href="http://www.youtube.com/user/ContinuumIO" title="Check out Continuum's support videos on YouTube" target="_blank"><img src="/img/youtube_header.png" alt="Check out Continuum's support videos on YouTube" width="33" height="33"></a>-->
						</section>
                    </article>
                    <article class="span2 footer_align_left">
						<b><a href="http://www.continuum.io/python-for-big-data.html" title="Products" class="footer_links">Products</a></b><br/>
						<a href="http://www.continuum.io/python-for-big-data.html" title="Python for Big Data" class="footer_links">Python for Big Data</a><br/>
						<a href="http://store.continuum.io/cshop/anaconda" title="Anaconda" class="footer_links">Anaconda</a><br/>
						<a href="http://store.continuum.io/cshop/iopro" title="IOPro" class="footer_links">IOPro</a><br/>
						<a href="http://store.continuum.io/cshop/numbapro" title="NumbaPro" class="footer_links">Numba Pro</a><br/>
						<a href="http://www.continuum.io/downloads.html" title="Downloads" class="footer_links">Downloads</a><br/>
						<br/>
						<b><a href="consulting.html" title="Solutions" class="footer_links">Consulting</a></b><br/>
						<br/>
						<b><a href="http://www.continuum.io/training.html" title="Training" class="footer_links">Training</a></b><br/>
						<!--<a href="http://www.continuum.io/course-descriptions.html" title="Courses" class="footer_links">Courses</a><br/>
						<a href="http://www.continuum.io/calendar.html" title="Calendar" class="footer_links">Calendar</a><br/>-->
						<br/>
						<b><a href="http://www.continuum.io/support.html" title="Support" class="footer_links">Support</a></b><br/>
					</article>
                    <article class="span1 footer_align_left">
						<!--<b><a href="http://www.continuum.io/index.php/blog" title="Expertise" class="footer_links">Expertise</a></b><br/>-->				
						<b><a href="http://www.continuum.io/developer-resources.html" title="Developer Resources" class="footer_links">Developers</a></b><br/>
						<br/>
						<b><a href="http://www.continuum.io/about-continuum.html" title="Company" class="footer_links">Company</a></b><br/>
						<a href="http://www.continuum.io/our-team.html" title="Our Team" class="footer_links">Our Team</a><br/>
						<a href="http://www.continuum.io/careers.html" title="Careers" class="footer_links">Careers</a><br/>
						<a href="http://www.continuum.io/index.php/blog" title="Blog" class="footer_links">Blog</a><br/>
						<a href="http://www.continuum.io/press/index.php" title="Press Releases" class="footer_links">Press</a><br/>
						<a href="http://www.numfocus.org" title="NumFocus" class="footer_links">NumFocus</a><br/>
						<br/>
						<b><a href="http://www.continuum.io/support.html" title="Contact Us" class="footer_links">Contact</a></b>
					</article>
					<article class="span4">
                    	<section class="footer_twitter"><a href="http://www.twitter.com/continuumio" class="footer_links" target="_blank">Follow us on Twitter!</a></section>
                   		<section id="jstwitter"></section>
						<section class="footer_copyright">&copy; 2012 Continuum Analytics</section>
					</article>
				</section>
			</section>
		</footer>