<h3><a href="python-for-quants.html" title="Python for Quants and Engineers">Python for Quants and Engineers</a></h3></<br/><br/>
<section class="span1 calendar"> 
	<span class="month">Oct</span>
	<span class="day">2</span>
</section>
 <section class="span3 course">
   <a href="/calendar.html" title="Training Calendar"><strong>Austin, TX<br/>October 2 - 5</strong></a>
</section>
<br/><br/>
<section class="span1 calendar"> 
	<span class="month">Dec</span>
	<span class="day">4</span>
</section>
 <section class="span3 course">
   <a href="/calendar.html" title="Training Calendar"><strong>New York, NY<br/>December 4 - 7</strong></a>
</section>
<br/><br/>
<section class="span1 calendar"> 
	<span class="month">March</span>
	<span class="day">5</span>
</section>
 <section class="span3 course">
	<a href="/calendar.html" title="Training Calendar"><strong>Chicago, IL<br/>March 5 - 8</strong></a>
</section>
<br/><br/>
<section class="span1 calendar"> 
	<span class="month">June</span>
	<span class="day">4</span>
</section>
 <section class="span3 course">
	<a href="/calendar.html" title="Training Calendar"><strong>New York, NY<br/>June 4 - 7</strong></a>
</section>
<br/><br/>
<section class="span1 calendar"> 
	<span class="month">Sept</span>
	<span class="day">3</span>
</section>
 <section class="span3 course">
   <a href="/calendar.html" title="Training Calendar"><strong>London, England<br/>September 3 - 6</strong></a>
</section>