<header class="header">
            <section class="header_all"></section>
            <section class="header_left"></section>
            <section class="header_right"></section>
            <section class="container header_center">
              <h1>Continuum Analytics</h1>
                <article class="tagline">Python Visualization and Data Exploration</article>
                <nav class="navbar">
                    <section class="navbar-inner">
                        <section class="container">
                        <ul class="nav">
							<li class="dropdown"><a href="/index.html" title="Continuum Analytics">Home</a></li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="/products.html">Products&nbsp; <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/python-for-big-data.html" title="Python for Big Data">Python for Big Data</a></li>
                                    <li><a href="/anaconda.html" title="Anaconda">Anaconda</a></li>
                                    <!--<li><a href="/blaze.html" title="Blaze">Blaze</a></li>-->
                                    <!--<li><a href="/excel-plug-in.html" title="Excel Plug-in">Excel Plug-in</a></li>-->
                                    <li><a href="/downloads.html" title="Downloads">Downloads</a></li>
                                </ul>
                            </li>
                            <li class="dropdown"><a href="/consulting.html" title="">Consulting</a></li>
							<li class="dropdown"><a href="/training.html" title="">Training</a></li>
                            <!--<li class="dropdown">
                                <a data-target="#" href="/training.html" title="Training" class="dropdown-toggle" data-toggle="dropdown">Training&nbsp; <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/training.html" title="Course Descriptions">Courses</a></li>
                                    <li><a href="/training.html" title="Course Schedules">Calendar</a></li>
                                </ul>
                            </li>-->
                            <li class="dropdown"><a href="/support.html">Support</a></li>
                            <li class="dropdown"><a href="/developer-resources.html">Developers</a></li>
                          <li class="dropdown"><a data-target="#" href="/company.html" title="Company" class="dropdown-toggle" data-toggle="dropdown">Company&nbsp; <b class="caret"></b></a>
                                <ul class="dropdown-menu">
									<li><a href="/about-continuum.html" title="About Continuum">About Us</a></li>
                                    <li><a href="/our-team.html" title="Team">Our Team</a></li>
                                    <li><a href="/careers.html" title="Careers">Careers</a></li>
									<li><a href="/index.php/blog">Blog</a></li>
                                    <li><a href="/press/index.php" title="Press Releases">Press Releases</a></li>
                                    <li><a href="http://www.numfocus.org" title="NumFocus" target="_blank">NumFocus</a></li>
                                </ul>
						  </li>
                          <li class="dropdown">
                              <div class="social_media_header">&nbsp;
                                  <a href="http://plus.google.com/108011804375544975017" title="Circle Continuum Analytics on Google+" target="_blank"><img src="/img/gplus_header.png" alt="Circle Continuum Analytics on Google+" width="33" height="33"></a>
                                  <a href="http://www.twitter.com/continuumio" title="Follow @continuumio on Twitter" target="_blank"><img src="/img/twitter_header.png" alt="Follow @continuumio on Twitter" width="33" height="33"></a>
                                  <a href="http://www.linkedin.com/company/continuum-analytics-inc-" title="Follow Continuum Analytics on LinkedIn" target="_blank"><img src="/img/linkedin_header.png" alt="Follow Continuum Analytics on LinkedIn" width="33" height="33"></a>
                                  <a href="http://www.facebook.com/ContinuumAnalytics" title="Like Continuum Analytics on Facebook" target="_blank"><img src="/img/facebook_header.png" alt="Like Continuum Analytics on Facebook" width="33" height="33"></a>
                                  <a href="http://www.youtube.com" title="Check out Continuum's support videos on YouTube" target="_blank"><img src="/img/youtube_header.png" alt="Check out Continuum's support videos on YouTube" width="33" height="33"></a>
                              </div>
                          </li>
                        </ul>
                        </section>
                  </section>
              </nav>
            </section>
        </header>